// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS5Nzh0P1rmbxZkvHgwtyJjycUxzyqk_s',
    appId: '1:143927446985:web:45cc001cbccf1036f66c18',
    messagingSenderId: '143927446985',
    projectId: 'fitness-app-1ef2e',
    authDomain: 'fitness-app-1ef2e.firebaseapp.com',
    storageBucket: 'fitness-app-1ef2e.firebasestorage.app',
    measurementId: 'G-7JX02460XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXpJ4FKtRQcDY2GB-kpJi9g3P5piqwKa4',
    appId: '1:143927446985:android:bc0e07230d5aa746f66c18',
    messagingSenderId: '143927446985',
    projectId: 'fitness-app-1ef2e',
    storageBucket: 'fitness-app-1ef2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg9lAQZB5ZkZuWnGF2YZv_lQbWza1MNy0',
    appId: '1:143927446985:ios:5b770039a40fff84f66c18',
    messagingSenderId: '143927446985',
    projectId: 'fitness-app-1ef2e',
    storageBucket: 'fitness-app-1ef2e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg9lAQZB5ZkZuWnGF2YZv_lQbWza1MNy0',
    appId: '1:143927446985:ios:f9356a3447dc49d1f66c18',
    messagingSenderId: '143927446985',
    projectId: 'fitness-app-1ef2e',
    storageBucket: 'fitness-app-1ef2e.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS5Nzh0P1rmbxZkvHgwtyJjycUxzyqk_s',
    appId: '1:143927446985:web:944bebebaa76c6d1f66c18',
    messagingSenderId: '143927446985',
    projectId: 'fitness-app-1ef2e',
    authDomain: 'fitness-app-1ef2e.firebaseapp.com',
    storageBucket: 'fitness-app-1ef2e.firebasestorage.app',
    measurementId: 'G-WZMSMW2CBS',
  );

}